###应用监控的配置
management:
  endpoints:
    web:
      # 设置监控访问的应用路径，默认是/actuator
      # base-path: /moitor
      exposure:
        # 暴露监控访问接口，默认是/health和info
        include: "*"
        # 显示屏蔽监控访问接口
        exclude: env,metrics
  # 开放关闭应用程序端点，不建议开启
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
