###程序的端口
server:
  port: 8443
###分开设置配置文件
spring:
  profiles:
    active: datasource,thymeleaf,actuator
    #定义项目的静态资源
  #resources:
    #static-locations: classpath:/static/
  #定义项目的静态资源
  #mvc:
   # static-path-pattern: /static/**
  #spring-boot-admin-starter-client 监控客户端的相关配置
  boot:
    admin:
      client:
        # 服务端的请求地址
        url: http://localhost:8081
        username: admin
        password: 123456
        instance:
          service-base-url: http://localhost:8443
###日志服务器
#logging:
#  config: classpath:logback-spring.xml
