###程序的端口
server:
  port: 8002
spring:
  application:
    name: yls_data_backup

data:
  backup:
    datasource:
      host: localhost
      userName: root
      password: root
      database: yls_privilege_management
